spring:
  application:
    name: junction-backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: never

spot:
  update:
    url: https://raw.githubusercontent.com/Junction2024-Tiramisu/junction-backend/main/data-pipeline/processed-data/
